//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uppgift_4_Mertan.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programs
    {
        public int Id { get; set; }
        public int ChannelId { get; set; }
        public string Title { get; set; }
        public string Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string Category { get; set; }
        public string Resume { get; set; }
    
        public virtual Channels Channels { get; set; }
    }
}
