//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uppgift_4_Mertan.Models.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users_Chanels
    {
        [Required(ErrorMessage = "Du måste fylla i kod fältet någon siffra.")]
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ChannelId { get; set; }
    
        public virtual Channels Channels { get; set; }
        public virtual Users Users { get; set; }
    }
}
